#!/bin/bash -el

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

cd /

SOURCE_DIR=/var/lib/tsuru

if [ $# -lt 1 ]
then
	echo "Usage:"
	echo
	echo "  % $0 <type> [param_1] [param_2] ... [param_n]"
	exit 1
fi

function archive_deploy() {
	if [ -d $CURRENT_DIR ]
	then
		sudo rm -rf $CURRENT_DIR
	fi
	mkdir -p $CURRENT_DIR
	curl -sSfNL $1 -o /tmp/archive.tar.gz
	tar -C $CURRENT_DIR -xzf /tmp/archive.tar.gz
	rm /tmp/archive.tar.gz
}

function pre_deploy() {
	if [ -f ${APP_DIR}/.default_procfile ]
	then
		rm ${APP_DIR}/.default_procfile ${CURRENT_DIR}/Procfile
	fi
}

function post_deploy() {
	if [ ! -f ${CURRENT_DIR}/Procfile ] && [ -f ${SOURCE_DIR}/default/Procfile ]
	then
		cp ${SOURCE_DIR}/default/Procfile ${CURRENT_DIR}/Procfile
		touch ${APP_DIR}/.default_procfile
	fi
}


source ${SOURCE_DIR}/base/rc/config
source ${SOURCE_DIR}/base/rc/os_dependencies

pre_deploy
case $1 in
	"archive")
		archive_deploy $2
		shift; shift
		;;
	*)
		echo "FATAL: this deployment method is no longer supported"
		exit 1
		;;
esac
post_deploy

os_dependencies
