#!/bin/bash -el

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

mkdir -p /home/application
useradd -m ${USER} -s /bin/bash
chown ${USER}:${USER} /home/application

cp ${SOURCE_DIR}/base/apt.conf.d/local /etc/apt/apt.conf.d/local
buildDeps='curl sudo jq rsync netcat-openbsd net-tools telnet vim-tiny lsof apt-transport-https'
apt-get update
apt-get install -y --no-install-recommends $buildDeps

echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
curl -Lk https://packagecloud.io/install/repositories/tsuru/stable/script.deb.sh | bash
apt-get install -y deploy-agent

mkdir -p ${SOURCE_DIR}/default

echo "export DEBIAN_FRONTEND=noninteractive" >> /etc/profile
