#!/bin/bash

# Copyright 2022 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current
USER=ubuntu
USER_GID=1000
USER_UID=1000
HOME=/home/${USER}
UBUNTU_RELEASE=$(. /etc/lsb-release && echo ${DISTRIB_CODENAME})

echo_debug() {
  if [ ! -z "${TSURU_DEBUG}" ]; then
    echo "$@"
  fi
}
