#!/bin/bash

# Copyright 2022 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# removes all '#' and all characters afterwards; trim whitespaces; carriage return and empty lines
function cat_without_hash_comments() {
  local file_path=${1}
  cat ${file_path} |
    sed "s/#.*$//g" |
    sed "s/^[[:space:]]*//g" |
    sed "s/[[:space:]]*$//g" |
    sed "s/\r$//" |
    sed "/^$/d"
}

function os_dependencies() {
  if [[ -f "${CURRENT_DIR}/repositories.apt" ]]; then
    echo_debug ">>> repositories.apt found: adding extra APT repositories"

    while read repo; do
      add_repository ${repo}
    done < <(cat_without_hash_comments "${CURRENT_DIR}/repositories.apt")
  fi

  if [[ -f "${CURRENT_DIR}/requirements.apt" ]]; then
    echo_debug ">>> requirements.apt found: installing system package(s) from it"
    sudo -E apt-get update || true
    sudo -E apt-get install -y --force-yes --no-install-recommends \
      $(cat_without_hash_comments "${CURRENT_DIR}/requirements.apt")
  fi
}

function add_repository() {
  local repository=${1}
  local repository_entries
  local ppa
  local fingerprint
  local user
  local filesum

  case ${repository} in
  deb*)
    repository_entries=${*}
    ;;

  *)
    ppa=${repository/#ppa:/}
    fingerprint=${2:-${ppa}}
    user=$(echo "${ppa}" | awk -F / '{print $1}')

    repository_entries=$(
      cat <<-EOF
deb [signed-by=/usr/share/keyrings/${user}.gpg] https://ppa.launchpadcontent.net/${ppa}/ubuntu ${UBUNTU_RELEASE} main
deb-src [signed-by=/usr/share/keyrings/${user}.gpg] https://ppa.launchpadcontent.net/${ppa}/ubuntu ${UBUNTU_RELEASE} main
EOF
    )

    get_ppa_key "${fingerprint}" "${user}"
    ;;
  esac

  filesum=$(echo "${repository_entries}" | sha1sum | awk '{print $1}')
  echo "${repository_entries}" | sudo -E tee "/etc/apt/sources.list.d/tsuru_${filesum}.list" >/dev/null 2>&1
}

function get_ppa_key() {
  local ppa_or_fingerprint=${1}
  local user=${2}
  local fingerprint
  local repo

  if [[ ${ppa_or_fingerprint} =~ ^0x.+ ]]; then
    fingerprint=${ppa_or_fingerprint}
  else
    repo=$(echo "${ppa_or_fingerprint}" | awk -F / '{print $2}')
    api_url="https://launchpad.net/api/1.0/~${user}/+archive/ubuntu/${repo}"
    fingerprint=$(curl -sS "${api_url}" | jq -r ".signing_key_fingerprint")
  fi

  sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/"${user}".gpg --keyserver keyserver.ubuntu.com --recv-keys "${fingerprint}"
}
