#!/bin/bash

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current
USER=ubuntu
HOME=/home/${USER}
UBUNTU_RELEASE=$(test -f /etc/lsb-release && source /etc/lsb-release && echo $DISTRIB_CODENAME || echo trusty)

function get_ppa_key() {
	if [[ $1 =~ ^0x.+ ]]; then
		fingerprint=$1
	else
		user=$(echo $1 | awk -F / '{print $1}')
		repo=$(echo $1 | awk -F / '{print $2}')
		api_url="https://launchpad.net/api/1.0/~${user}/+archive/ubuntu/${repo}"
		fingerprint=$(curl -sS "${api_url}" | jq -r ".signing_key_fingerprint")
	fi
	sudo -E apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv ${fingerprint}
}

function add_repository() {
  set +e
	ppa=$(echo $1 | grep "^ppa:\(.*\)$")
	set -e
	if [ "${ppa}" = "${1}" ]; then
		ppa=$(echo $1 | awk -F : '{print $2}')
		repository="deb http://ppa.launchpad.net/${ppa}/ubuntu ${UBUNTU_RELEASE} main"
		get_ppa_key $ppa
	elif [[ "$*" =~ ^deb(-src)?.+ ]]; then
		repository=$*
	else
		repository=$1
		if [[ "$2" =~ ^0x.+ ]]; then
			get_ppa_key $2
		fi
	fi
	filesum=$(echo $repository | sha1sum | awk '{print $1}')
	filename="tsuru_${filesum}.list"
	echo "$repository" | sudo -E tee >/dev/null 2>&1 /etc/apt/sources.list.d/${filename}
}

function echo_debug() {
	if [ ! -z "${TSURU_DEBUG}" ]; then
		echo "$@"
	fi
}
