#!/bin/bash -el

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

function cat_without_hash_comments() {
  # removes all '#' and all characters afterwards
  # and empty lines in case there where lines that start with '#'
  (sed "s/#.*$//g" | sed "/^[[:space:]]*$/d") < "$1"
}

function os_dependencies() {
    if [ -f ${CURRENT_DIR}/repositories.apt ]; then
        source /var/lib/tsuru/base/rc/config
        while read repo ; do
            add_repository ${repo}
        done < <(cat_without_hash_comments "${CURRENT_DIR}/repositories.apt")
    fi
    if [ -f ${CURRENT_DIR}/requirements.apt ]; then
        set +e
        requirements_without_comments="$(cat_without_hash_comments ${CURRENT_DIR/requirements.apt})"
        sudo -E apt-get install $requirements_without_comments -y --force-yes --no-install-recommends
        status=$?
        set -e
        if [ ${status} != 0 ]; then
            sudo apt-get update
            sudo -E apt-get install $requirements_without_comments -y --force-yes --no-install-recommends
        fi
    fi
}
