name: CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        version: ["20.04", "22.04", "24.04", latest]

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: test against Ubuntu ${{ matrix.version }}
      run: |-
        UBUNTU_VERSION_TEST=${{ matrix.version }} make test

  publish:
    if: contains(github.ref, 'refs/heads/master')

    needs: [test]

    strategy:
      matrix:
        version: ["20.04", "22.04", "24.04", latest]

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: push image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: tsuru/base-platform:${{ matrix.version }}
        platforms: linux/amd64, linux/arm64
        build-args: ubuntu_version=${{ matrix.version }}
