name: CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        version: ["22.04", latest]

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: test against Ubuntu ${{ matrix.version }}
      run: |-
        UBUNTU_VERSION_TEST=${{ matrix.version }} make test

  publish:
    if: contains(github.ref, 'refs/heads/master')

    needs: [test]

    strategy:
      matrix:
        version: ["22.04", latest]

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: docker login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: build tsuru/base-platform:${{ matrix.version }}
      run: |-
        docker build --build-arg ubuntu_version=${{ matrix.version }} -t tsuru/base-platform:${{ matrix.version }} .

    - name: push tsuru/base-platform:${{ matrix.version }} to Docker Hub
      run: |-
        docker push tsuru/base-platform:${{ matrix.version }}
